---
framework: mocha
preRun:
     command:
        - npm ci
preMerge:
  env:
    BABEL_ENV: test
  pattern:
    - "./test/**.ts"
postMerge:
  env:
    BABEL_ENV: test
  pattern: 
    - "./test/**.ts"
postRun:
     command:
        - node --version
configFile: mocha.opts
version: 1.0